# Create or update Application Service; HTTP and HTTPS virtual services in one declaration

# Device 1

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    password: "{{BIGIPadminPassword}}"
    server: "{{deviceName1}}"
    user: "{{BIGIPadminUsername}}"
    validate_certs: no
  delegate_to: localhost

- name: Get BIG-IP Authentication Token from {{deviceName1}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProviderName":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{deviceName1}}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip1_auth_response
  retries: 30
  delay: 5
  until: "(bigip1_auth_response | success) and (bigip1_auth_response.status == 200)"

- name: Assign Auth Token to Variable
  set_fact:
    bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

- name: Prepare the AS3 declaration
  template: src="{{ role_path }}/files/as3_ssl_redirect.json" dest="{{ role_path }}/files/{{ serviceName }}_declaration.json"
  delegate_to: localhost

- name: Validate {{deviceName1}} AS3 Rest Worker is ready
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: GET
    url: "https://{{deviceName1}}/mgmt/shared/appsvcs/available"
    validate_certs: no
  retries: 30
  delay: 5
  register: result
  until: "(result | success) and (result.status == 200)"

- name: Create or update {{ serviceName }}; HTTP and HTTPS virtual services in one declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ serviceName }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: POST
    status_code: 200
    url: "https://{{deviceName1}}/mgmt/shared/appsvcs/declare"
    validate_certs: no